modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersiveArchitects/issues"
license = "GNU"

[[mods]]
modId = "immersive_architects"
version = "${version}"
displayName = "Immersive Architects"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ImmersiveArchitects"
authors = "Luke100000"
description = "Various architectural features."
logoFile = "logoFile.png"

[[dependencies.immersive_architects]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_architects]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
